// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Core__List = require("../../src/core/Core__List.bs.js");
var RealmNoUpdate = require("../../src/RealmNoUpdate.bs.js");

function toggle(entry) {
  return RealmNoUpdate.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.map((function (it) {
                                var match = it[/* id */0] === entry[/* id */0];
                                if (match) {
                                  return /* record */[
                                          /* id */entry[/* id */0],
                                          /* title */entry[/* title */1],
                                          /* completed */!entry[/* completed */2],
                                          /* editing */entry[/* editing */3],
                                          /* created */entry[/* created */4]
                                        ];
                                } else {
                                  return it;
                                }
                              }), model[/* entries */0]),
                        /* visibility */model[/* visibility */1]
                      ];
              }));
}

function edit(entry, editing) {
  return RealmNoUpdate.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.map((function (it) {
                                var match = it[/* id */0] === entry[/* id */0];
                                if (match) {
                                  return /* record */[
                                          /* id */entry[/* id */0],
                                          /* title */entry[/* title */1],
                                          /* completed */entry[/* completed */2],
                                          /* editing */editing,
                                          /* created */entry[/* created */4]
                                        ];
                                } else {
                                  return it;
                                }
                              }), model[/* entries */0]),
                        /* visibility */model[/* visibility */1]
                      ];
              }));
}

function remove(entry) {
  return RealmNoUpdate.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.filter((function (it) {
                                  return it[/* id */0] !== entry[/* id */0];
                                }))(model[/* entries */0]),
                        /* visibility */model[/* visibility */1]
                      ];
              }));
}

var clearCompleted = RealmNoUpdate.Effect[/* update */2]((function (model) {
        return /* record */[
                /* entries */Core__List.filter((function (it) {
                          return !it[/* completed */2];
                        }))(model[/* entries */0]),
                /* visibility */model[/* visibility */1]
              ];
      }));

function changeVisibility(visibility) {
  return RealmNoUpdate.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */model[/* entries */0],
                        /* visibility */visibility
                      ];
              }));
}

exports.toggle = toggle;
exports.edit = edit;
exports.remove = remove;
exports.clearCompleted = clearCompleted;
exports.changeVisibility = changeVisibility;
/* clearCompleted Not a pure module */
