// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var RealmNoUpdate = require("../../src/RealmNoUpdate.bs.js");

function toggle(item) {
  return RealmNoUpdate.Cmd[/* make */0]((function (model) {
                return /* record */[
                        /* editing */model[/* editing */0],
                        /* items */List.map((function (it) {
                                var match = it[/* id */0] === item[/* id */0];
                                if (match) {
                                  return /* record */[
                                          /* id */item[/* id */0],
                                          /* title */item[/* title */1],
                                          /* completed */!item[/* completed */2],
                                          /* created */item[/* created */3]
                                        ];
                                } else {
                                  return it;
                                }
                              }), model[/* items */1])
                      ];
              }));
}

function edit(item) {
  return RealmNoUpdate.Cmd[/* make */0]((function (model) {
                console.log("edit");
                return /* record */[
                        /* editing */item[/* id */0],
                        /* items */model[/* items */1]
                      ];
              }));
}

function remove(item) {
  return RealmNoUpdate.Cmd[/* make */0]((function (model) {
                return /* record */[
                        /* editing */model[/* editing */0],
                        /* items */List.filter((function (it) {
                                  return it[/* id */0] !== item[/* id */0];
                                }))(model[/* items */1])
                      ];
              }));
}

var clearCompleted = RealmNoUpdate.Cmd[/* make */0]((function (model) {
        return /* record */[
                /* editing */model[/* editing */0],
                /* items */List.filter((function (it) {
                          return !it[/* completed */2];
                        }))(model[/* items */1])
              ];
      }));

exports.toggle = toggle;
exports.edit = edit;
exports.remove = remove;
exports.clearCompleted = clearCompleted;
/* clearCompleted Not a pure module */
