// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Realm = require("../../src/Realm.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var TodoTextInput = require("./TodoTextInput.bs.js");

var addTextInput = Realm.Core[/* |> */11](TodoTextInput.view("new-todo", "What needs to be done?", ""), Curry._2(Realm.React[/* Html */0][/* map */17], (function (param) {
            return "";
          }), (function (model, name) {
            return /* record */[
                    /* entries */Pervasives.$at(model[/* entries */0], /* :: */[
                          Model.Todo[/* make */1](name),
                          /* [] */0
                        ]),
                    /* visibility */model[/* visibility */1]
                  ];
          })));

function view(param) {
  return Curry._4(Realm.React[/* Html */0][/* header */6], undefined, undefined, undefined, /* :: */[
              Curry._4(Realm.React[/* Html */0][/* h1 */7], undefined, undefined, undefined, /* :: */[
                    Curry._1(Realm.React[/* Html */0][/* text */2], "todos"),
                    /* [] */0
                  ]),
              /* :: */[
                addTextInput,
                /* [] */0
              ]
            ]);
}

exports.addTextInput = addTextInput;
exports.view = view;
/* addTextInput Not a pure module */
