// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var RealmNoUpdate = require("../../src/RealmNoUpdate.bs.js");
var TodoTextInput = require("./TodoTextInput.bs.js");

var partial_arg = "What needs to be done?";

function partial_arg$1(param) {
  return TodoTextInput.view("new-todo", partial_arg, "", param);
}

function addTextInput(param) {
  return RealmNoUpdate.map((function (param) {
                return "";
              }), (function (model, name) {
                return /* record */[
                        /* editing */model[/* editing */0],
                        /* items */Pervasives.$at(model[/* items */1], /* :: */[
                              Model.Todo[/* make */1](name),
                              /* [] */0
                            ])
                      ];
              }), partial_arg$1, param);
}

function view(param) {
  return Curry._4(Model.Html[/* header */8], undefined, undefined, undefined, /* :: */[
              Curry._4(Model.Html[/* h1 */9], undefined, undefined, undefined, /* :: */[
                    Curry._1(Model.Html[/* text */4], "todos"),
                    /* [] */0
                  ]),
              /* :: */[
                addTextInput,
                /* [] */0
              ]
            ]);
}

exports.addTextInput = addTextInput;
exports.view = view;
/* Model Not a pure module */
