// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Model = require("./Model.bs.js");
var TodoApp = require("./TodoApp.bs.js");
var RealmNoUpdate = require("../../src/RealmNoUpdate.bs.js");

function init(param) {
  return /* record */[
          /* editing */undefined,
          /* items : :: */[
            Model.Todo[/* make */1]("Item 1"),
            /* :: */[
              Model.Todo[/* make */1]("Item 2"),
              /* [] */0
            ]
          ]
        ];
}

function view(param) {
  return TodoApp.view(param[/* items */1], param[/* editing */0]);
}

RealmNoUpdate.mountHtml("todoapp")(init, view);

exports.init = init;
exports.view = view;
/*  Not a pure module */
