// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Realm = require("../../src/Realm.bs.js");
var TodoApp = require("./TodoApp.bs.js");

function init(param) {
  return Realm.Task[/* const */1](/* record */[
              /* entries : :: */[
                Model.Todo[/* make */1]("Item 1"),
                /* :: */[
                  Model.Todo[/* make */1]("Item 2"),
                  /* [] */0
                ]
              ],
              /* visibility */"All"
            ]);
}

var infoFooter = Curry._4(Model.Html[/* footer */5], undefined, "info", undefined, /* :: */[
      Curry._4(Model.Html[/* p */14], undefined, undefined, undefined, /* :: */[
            Curry._1(Model.Html[/* text */3], "Double-click to edit a todo"),
            /* [] */0
          ]),
      /* :: */[
        Curry._4(Model.Html[/* p */14], undefined, undefined, undefined, /* :: */[
              Curry._1(Model.Html[/* text */3], "Written by "),
              /* :: */[
                Curry._5(Model.Html[/* a */15], "https://github.com/glennsl", undefined, undefined, undefined, /* :: */[
                      Curry._1(Model.Html[/* text */3], "Glenn Slotte"),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]),
        /* :: */[
          Curry._4(Model.Html[/* p */14], undefined, undefined, undefined, /* :: */[
                Curry._1(Model.Html[/* text */3], "Part of "),
                /* :: */[
                  Curry._5(Model.Html[/* a */15], "http://todomvc.com", undefined, undefined, undefined, /* :: */[
                        Curry._1(Model.Html[/* text */3], "TodoMVC"),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]),
          /* [] */0
        ]
      ]
    ]);

function view(param) {
  return Curry._4(Model.Html[/* div */6], undefined, undefined, undefined, /* :: */[
              TodoApp.view(param[/* entries */0], param[/* visibility */1]),
              /* :: */[
                infoFooter,
                /* [] */0
              ]
            ]);
}

Realm.mountHtml("todoapp")(init, undefined, undefined, view, /* () */0);

exports.init = init;
exports.infoFooter = infoFooter;
exports.view = view;
/* infoFooter Not a pure module */
