// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Header = require("./Header.bs.js");
var TodoFooter = require("./TodoFooter.bs.js");
var MainSection = require("./MainSection.bs.js");

function view(items, editing) {
  return Curry._4(Model.Html[/* div */7], undefined, "todoapp", undefined, /* :: */[
              Header.view(/* () */0),
              /* :: */[
                MainSection.view(items, editing),
                /* :: */[
                  TodoFooter.view(items),
                  /* [] */0
                ]
              ]
            ]);
}

exports.view = view;
/* Model Not a pure module */
