// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("../../src/Realm.bs.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Greeting");

function make(className, placeholder, onEnter, initialValue, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var tmp = {
                className: className,
                value: self[/* state */1],
                onKeyDown: (function (e) {
                    return Curry._1(self[/* send */3], /* `KeyDown */[
                                -375877247,
                                e.keyCode
                              ]);
                  }),
                onChange: (function (e) {
                    return Curry._1(self[/* send */3], /* `ValueChanged */[
                                492430755,
                                e.target.value
                              ]);
                  })
              };
              if (placeholder !== undefined) {
                tmp.placeholder = Caml_option.valFromOption(placeholder);
              }
              return React.createElement("input", tmp);
            }),
          /* initialState */(function (param) {
              return initialValue;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action[0] >= 492430755) {
                return /* Update */Block.__(0, [action[1]]);
              } else if (action[1] === 13) {
                Curry._1(onEnter, state);
                return /* Update */Block.__(0, [""]);
              } else {
                return /* NoUpdate */0;
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var TextInput = /* module */[
  /* component */component,
  /* make */make
];

function view(className, placeholder, initialValue, dispatch) {
  return ReasonReact.element(undefined, undefined, make(className, placeholder, (function (value) {
                    return Curry._1(dispatch, Realm.Effect[/* const */1](value));
                  }), initialValue, /* array */[]));
}

exports.TextInput = TextInput;
exports.view = view;
/* component Not a pure module */
