// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Realm = require("../../src/Realm.bs.js");
var Actions = require("./Actions.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var TodoTextInput = require("./TodoTextInput.bs.js");

function editTextInput(initialValue) {
  return Realm.Core[/* |> */11](TodoTextInput.view("edit", undefined, initialValue), Curry._1(Realm.React[/* Html */0][/* map */17], Curry._2(Realm.Core[/* Effect */15][/* map */5], (function (param) {
                        return "";
                      }), (function (model, name) {
                        return /* record */[
                                /* entries */Pervasives.$at(model[/* entries */0], /* :: */[
                                      Model.Todo[/* make */1](name),
                                      /* [] */0
                                    ]),
                                /* visibility */model[/* visibility */1]
                              ];
                      }))));
}

function view(entry) {
  var match = entry[/* editing */3];
  var match$1 = entry[/* editing */3];
  return Curry._4(Realm.React[/* Html */0][/* li */11], undefined, match ? "editing" : "", undefined, /* :: */[
              Curry._4(Realm.React[/* Html */0][/* div */4], undefined, "view", undefined, /* :: */[
                    Curry._6(Realm.React[/* Html */0][/* input */16], undefined, /* `Checkbox */[
                          111644259,
                          entry[/* completed */2]
                        ], undefined, "toggle", /* :: */[
                          Curry._1(Realm.React[/* Html */0][/* Attr */0][/* onChange */6], Actions.toggle(entry)),
                          /* [] */0
                        ], /* [] */0),
                    /* :: */[
                      Curry._5(Realm.React[/* Html */0][/* label */15], undefined, /* :: */[
                            Curry._1(Realm.React[/* Html */0][/* Attr */0][/* onDoubleClick */5], Actions.edit(entry, true)),
                            /* [] */0
                          ], undefined, undefined, /* :: */[
                            Curry._1(Realm.React[/* Html */0][/* text */2], entry[/* title */1]),
                            /* [] */0
                          ]),
                      /* :: */[
                        Curry._4(Realm.React[/* Html */0][/* button */3], undefined, "destroy", /* :: */[
                              Curry._1(Realm.React[/* Html */0][/* Attr */0][/* onClick */4], Actions.remove(entry)),
                              /* [] */0
                            ], /* [] */0),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* :: */[
                match$1 ? editTextInput(entry[/* title */1]) : Realm.React[/* Html */0][/* null */1],
                /* [] */0
              ]
            ]);
}

exports.editTextInput = editTextInput;
exports.view = view;
/* Realm Not a pure module */
