// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Actions = require("./Actions.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var RealmNoUpdate = require("../../src/RealmNoUpdate.bs.js");
var TodoTextInput = require("./TodoTextInput.bs.js");

function editTextInput(initialValue) {
  return (function (param) {
      return RealmNoUpdate.map((function (param) {
                    return "";
                  }), (function (model, name) {
                    return /* record */[
                            /* editing */model[/* editing */0],
                            /* items */Pervasives.$at(model[/* items */1], /* :: */[
                                  Model.Todo[/* make */1](name),
                                  /* [] */0
                                ])
                          ];
                  }), (function (param) {
                    return TodoTextInput.view("edit", undefined, initialValue, param);
                  }), param);
    });
}

function view(item, isEditing) {
  var func = Model.Html[/* input */18];
  var arg = /* :: */[
    Curry._1(Model.Html[/* Attr */1][/* onChange */6], Actions.toggle(item)),
    /* [] */0
  ];
  var arg_001 = item[/* completed */2];
  var arg$1 = /* `Checkbox */[
    111644259,
    arg_001
  ];
  var arg$2 = function (param, param$1) {
    return Curry._5(func, param, param$1, "toggle", arg, arg$1);
  };
  return Curry._4(Model.Html[/* li */13], undefined, isEditing ? "editing" : "", undefined, /* :: */[
              Curry._4(Model.Html[/* div */7], undefined, "view", undefined, /* :: */[
                    (function (eta) {
                        return Curry._1(arg$2(undefined, undefined), eta);
                      }),
                    /* :: */[
                      Curry._5(Model.Html[/* label */17], undefined, /* :: */[
                            Curry._1(Model.Html[/* Attr */1][/* onDoubleClick */5], Actions.edit(item)),
                            /* [] */0
                          ], undefined, undefined, /* :: */[
                            Curry._1(Model.Html[/* text */4], item[/* title */1]),
                            /* [] */0
                          ]),
                      /* :: */[
                        Curry._4(Model.Html[/* button */5], undefined, "destroy", /* :: */[
                              Curry._1(Model.Html[/* Attr */1][/* onClick */4], Actions.remove(item)),
                              /* [] */0
                            ], /* [] */0),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* :: */[
                isEditing ? editTextInput(item[/* title */1]) : Model.Html[/* null */3],
                /* [] */0
              ]
            ]);
}

exports.editTextInput = editTextInput;
exports.view = view;
/* Model Not a pure module */
