// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Realm = require("../../src/Realm.bs.js");
var Actions = require("./Actions.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var TodoTextInput = require("./TodoTextInput.bs.js");

function editTextInput(initialValue) {
  return Realm.Core[/* |> */11](TodoTextInput.view("edit", undefined, initialValue), (function (param, param$1) {
                return Realm.map((function (param) {
                              return "";
                            }), (function (model, name) {
                              return /* record */[
                                      /* entries */Pervasives.$at(model[/* entries */0], /* :: */[
                                            Model.Todo[/* make */1](name),
                                            /* [] */0
                                          ]),
                                      /* visibility */model[/* visibility */1]
                                    ];
                            }), param, param$1);
              }));
}

function view(entry) {
  var match = entry[/* editing */3];
  var match$1 = entry[/* editing */3];
  return Curry._4(Model.Html[/* li */11], undefined, match ? "editing" : "", undefined, /* :: */[
              Curry._4(Model.Html[/* div */5], undefined, "view", undefined, /* :: */[
                    Curry._6(Model.Html[/* input */16], undefined, /* `Checkbox */[
                          111644259,
                          entry[/* completed */2]
                        ], undefined, "toggle", /* :: */[
                          Curry._1(Model.Html[/* Attr */0][/* onChange */6], Actions.toggle(entry)),
                          /* [] */0
                        ], /* [] */0),
                    /* :: */[
                      Curry._5(Model.Html[/* label */15], undefined, /* :: */[
                            Curry._1(Model.Html[/* Attr */0][/* onDoubleClick */5], Actions.edit(entry, true)),
                            /* [] */0
                          ], undefined, undefined, /* :: */[
                            Curry._1(Model.Html[/* text */2], entry[/* title */1]),
                            /* [] */0
                          ]),
                      /* :: */[
                        Curry._4(Model.Html[/* button */3], undefined, "destroy", /* :: */[
                              Curry._1(Model.Html[/* Attr */0][/* onClick */4], Actions.remove(entry)),
                              /* [] */0
                            ], /* [] */0),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* :: */[
                match$1 ? editTextInput(entry[/* title */1]) : Model.Html[/* null */1],
                /* [] */0
              ]
            ]);
}

exports.editTextInput = editTextInput;
exports.view = view;
/* Model Not a pure module */
