// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("../../src/Realm.bs.js");
var TodoItem = require("./TodoItem.bs.js");

function view(entries, visibility) {
  var isVisible = function (entry) {
    switch (visibility) {
      case "Active" : 
          return !entry[/* completed */2];
      case "Completed" : 
          return entry[/* completed */2];
      default:
        return true;
    }
  };
  return Curry._4(Realm.React[/* Html */0][/* ul */10], undefined, "todo-list", undefined, Realm.Core[/* |> */11](Realm.Core[/* |> */11](entries, Curry._1(Realm.Core[/* List */3][/* filter */8], isVisible)), Curry._1(Realm.Core[/* List */3][/* map */4], TodoItem.view)));
}

exports.view = view;
/* Realm Not a pure module */
