// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var Actions = require("./Actions.bs.js");

var clearButton = Curry._4(Model.Html[/* button */5], undefined, "clear-completed", /* :: */[
      Curry._1(Model.Html[/* onClick */0], Actions.clearCompleted),
      /* [] */0
    ], /* :: */[
      Curry._1(Model.Html[/* text */4], "Clear completed"),
      /* [] */0
    ]);

function view(items) {
  var completedCount = List.length(List.filter((function (item) {
                return item[/* completed */2];
              }))(items));
  var activeCount = List.length(items) - completedCount | 0;
  var match = completedCount > 0;
  return Curry._4(Model.Html[/* footer */6], undefined, "footer", undefined, /* :: */[
              Curry._4(Model.Html[/* span */11], undefined, "todo-count", undefined, /* :: */[
                    Curry._4(Model.Html[/* strong */14], undefined, undefined, undefined, /* :: */[
                          Curry._1(Model.Html[/* text */4], String(activeCount)),
                          /* [] */0
                        ]),
                    /* :: */[
                      Curry._1(Model.Html[/* text */4], " items"),
                      /* [] */0
                    ]
                  ]),
              /* :: */[
                match ? clearButton : Model.Html[/* null */3],
                /* [] */0
              ]
            ]);
}

exports.clearButton = clearButton;
exports.view = view;
/* clearButton Not a pure module */
