// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Model = require("./Model.bs.js");
var TodoItem = require("./TodoItem.bs.js");
var Core__List = require("../../src/core/Core__List.bs.js");
var Realm__Core = require("../../src/core/Realm__Core.bs.js");

function view(entries, visibility) {
  var isVisible = function (entry) {
    switch (visibility) {
      case "Active" : 
          return !entry[/* completed */2];
      case "Completed" : 
          return entry[/* completed */2];
      default:
        return true;
    }
  };
  return Curry._4(Model.Html[/* ul */11], undefined, "todo-list", undefined, Realm__Core.$pipe$great(Realm__Core.$pipe$great(entries, Core__List.filter(isVisible)), (function (param) {
                    return Core__List.map(TodoItem.view, param);
                  })));
}

exports.view = view;
/* Model Not a pure module */
