// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Vdom = require("../../src/Vdom.bs.js");

var node = Vdom.$$Node[/* element */1](undefined, undefined, "strong", /* :: */[
      Vdom.Attribute[/* make */0](undefined, "class", "test-class"),
      /* [] */0
    ], /* :: */[
      Vdom.$$Node[/* text */0]("Hello"),
      /* :: */[
        Vdom.$$Node[/* element */1](undefined, undefined, "em", /* [] */0, /* :: */[
              Vdom.$$Node[/* text */0](" world"),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

Vdom.render(node, "root");

exports.node = node;
/* node Not a pure module */
