// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("../src/Realm.bs.js");

function init(param) {
  return "";
}

function fakeJob(name, delay) {
  return Realm.Core[/* |> */11](Realm.Core[/* |> */11](Curry._1(Realm.Core[/* Future */14][/* make */0], (function (resolve) {
                        return Realm.Core[/* |> */11]((console.log("start " + name), /* () */0), resolve);
                      })), Curry._1(Realm.Core[/* Future */14][/* andThen */2], (function (param) {
                        return Curry._1(Realm.Core[/* Time */17][/* delay */1], delay);
                      }))), Curry._1(Realm.Core[/* Future */14][/* map */3], (function (param) {
                    console.log("done " + name);
                    return /* () */0;
                  })));
}

var run = Curry._2(Realm.Core[/* Effect */15][/* do_ */3], (function (param) {
        return Curry._2(Realm.Core[/* Future */14][/* all2 */5], fakeJob("1", 1000), fakeJob("2", 500));
      }), (function (param, param$1) {
        return "done";
      }));

function view(model) {
  return Curry._4(Realm.React[/* Html */0][/* div */4], undefined, undefined, undefined, /* :: */[
              Curry._4(Realm.React[/* Html */0][/* button */3], undefined, undefined, /* :: */[
                    Curry._1(Realm.React[/* Html */0][/* Attr */0][/* onClick */4], run),
                    /* [] */0
                  ], /* :: */[
                    Curry._1(Realm.React[/* Html */0][/* text */2], "Start"),
                    /* [] */0
                  ]),
              /* :: */[
                Curry._1(Realm.React[/* Html */0][/* text */2], model),
                /* [] */0
              ]
            ]);
}

var App = Realm.React[/* SimpleApp */2](/* module */[
      /* init */init,
      /* view */view
    ]);

exports.App = App;
/* App Not a pure module */
