// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Stateful = require("./Stateful.bs.js");
var Stateless = require("./Stateless.bs.js");
var Composition = require("./Composition.bs.js");
var ReactInterop = require("./ReactInterop.bs.js");
var NoUpdate_Timer = require("./NoUpdate_Timer.bs.js");
var NoUpdate_Stateful = require("./NoUpdate_Stateful.bs.js");
var NoUpdate_Composition = require("./NoUpdate_Composition.bs.js");

Stateless.mount("stateless");

Stateful.mount("stateful");

ReactInterop.mount("react-interop");

Composition.mount("composition");

Curry._1(NoUpdate_Stateful.App[/* mount */0], "noupdate-stateful");

Curry._1(NoUpdate_Composition.App[/* mount */0], "noupdate-composition");

Curry._1(NoUpdate_Timer.App[/* mount */0], "noupdate-timer");

/*  Not a pure module */
