// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Stateful = require("./Stateful.bs.js");
var Stateless = require("./Stateless.bs.js");
var Composition = require("./Composition.bs.js");
var ReactInterop = require("./ReactInterop.bs.js");

Stateless.mount("stateless");

Stateful.mount("stateful");

ReactInterop.mount("react-interop");

Composition.mount("composition");

/*  Not a pure module */
