// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("../src/Realm.bs.js");
var Core__String = require("../src/core/Core__String.bs.js");

var Html = Realm.MakeHtml(/* module */[]);

function init(param) {
  return /* record */[/* count */0];
}

var click = Realm.Effect[/* update */2]((function (model) {
        return /* record */[/* count */model[/* count */0] + 1 | 0];
      }));

function view(model) {
  var message = "You've clicked this " + (Core__String.fromInt(model[/* count */0]) + " times(s)");
  return Curry._4(Html[/* div */6], undefined, undefined, undefined, /* :: */[
              Curry._4(Html[/* button */4], undefined, undefined, /* :: */[
                    Curry._1(Html[/* Attr */0][/* onClick */4], click),
                    /* [] */0
                  ], /* :: */[
                    Curry._1(Html[/* text */3], message),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function mount(at) {
  return Realm.mountHtml(at)(init, undefined, undefined, view, /* () */0);
}

exports.Html = Html;
exports.init = init;
exports.click = click;
exports.view = view;
exports.mount = mount;
/* Html Not a pure module */
