// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("../src/Realm.bs.js");

var Html = Realm.NoUpdate[/* Html */3](/* module */[]);

function init(param) {
  return /* record */[/* count */0];
}

var click = /* SetState */[(function (model) {
      return /* record */[/* count */model[/* count */0] + 1 | 0];
    })];

function view(model) {
  var message = "You've clicked this " + (String(model[/* count */0]) + " times(s)");
  return Curry._2(Html[/* div */4], /* [] */0, /* :: */[
              Curry._2(Html[/* button */5], /* :: */[
                    Curry._1(Html[/* onClick */0], click),
                    /* [] */0
                  ], /* :: */[
                    Curry._1(Html[/* text */3], message),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function mount(at) {
  return Realm.NoUpdate[/* mountHtml */2](at)(init, view);
}

exports.Html = Html;
exports.init = init;
exports.click = click;
exports.view = view;
exports.mount = mount;
/* Html Not a pure module */
