// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("../src/Realm.bs.js");

var Html = Curry._1(Realm.App[/* Html */0], /* module */[]);

function view(message, _) {
  return Curry._2(Html[/* div */3], /* [] */0, /* :: */[
              Curry._1(Html[/* text */2], message),
              /* [] */0
            ]);
}

exports.Html = Html;
exports.view = view;
/* Html Not a pure module */
