// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var not = /* () */0;

var or_ = /* () */0;

var and_ = /* () */0;

var xor = /* () */0;

exports.not = not;
exports.or_ = or_;
exports.and_ = and_;
exports.xor = xor;
/* No side effect */
