// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var add = /* () */0;

var subtract = /* () */0;

var multiply = /* () */0;

var divide = /* () */0;

var pow = /* () */0;

var toFloat = /* () */0;

var equals = /* () */0;

var notEquals = /* () */0;

var lessThan = /* () */0;

var greaterThan = /* () */0;

var lessThanOrEqual = /* () */0;

var greaterThanOrEqual = /* () */0;

var min = /* () */0;

var max = /* () */0;

var compare = /* () */0;

var modBy = /* () */0;

var remainderBy = /* () */0;

var negate = /* () */0;

var clamp = /* () */0;

var round = /* () */0;

var floor = /* () */0;

var ceiling = /* () */0;

var truncate = /* () */0;

var toInt = /* () */0;

var $$isNaN = /* () */0;

var $$isFinite = /* () */0;

exports.add = add;
exports.subtract = subtract;
exports.multiply = multiply;
exports.divide = divide;
exports.pow = pow;
exports.toFloat = toFloat;
exports.equals = equals;
exports.notEquals = notEquals;
exports.lessThan = lessThan;
exports.greaterThan = greaterThan;
exports.lessThanOrEqual = lessThanOrEqual;
exports.greaterThanOrEqual = greaterThanOrEqual;
exports.min = min;
exports.max = max;
exports.compare = compare;
exports.modBy = modBy;
exports.remainderBy = remainderBy;
exports.negate = negate;
exports.clamp = clamp;
exports.round = round;
exports.floor = floor;
exports.ceiling = ceiling;
exports.truncate = truncate;
exports.toInt = toInt;
exports.$$isNaN = $$isNaN;
exports.$$isFinite = $$isFinite;
/* No side effect */
