// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Core__Fn = require("./Core__Fn.bs.js");
var Core__List = require("./Core__List.bs.js");

var $great$great = Core__Fn.$great$great;

var $less$less = Core__Fn.$great$great;

var $pipe$great = Core__Fn.$pipe$great;

var $less$pipe = Core__Fn.$less$pipe;

var $plus$plus = Core__List.$plus$plus;

exports.$great$great = $great$great;
exports.$less$less = $less$less;
exports.$pipe$great = $pipe$great;
exports.$less$pipe = $less$pipe;
exports.$plus$plus = $plus$plus;
/* No side effect */
