// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var singleton = /* () */0;

var repeat = /* () */0;

var range = /* () */0;

var cons = /* () */0;

var map = List.map;

var mapi = /* () */0;

var foldl = List.fold_left;

var foldr = List.fold_right;

var filter = List.filter;

var filterMap = /* () */0;

var length = List.length;

var reverse = /* () */0;

var has = /* () */0;

var all = List.for_all;

var any = /* () */0;

var max = /* () */0;

var min = /* () */0;

var sum = /* () */0;

var product = /* () */0;

var append = /* () */0;

var concat = /* () */0;

var concatMap = /* () */0;

var intersperse = /* () */0;

var map2 = /* () */0;

var map3 = /* () */0;

var map4 = /* () */0;

var map5 = /* () */0;

var sort = /* () */0;

var sortBy = /* () */0;

var sortWith = /* () */0;

var isEmpty = /* () */0;

var head = /* () */0;

var tail = /* () */0;

var take = /* () */0;

var drop = /* () */0;

var partition = /* () */0;

var unzip = /* () */0;

var $plus$plus = Pervasives.$at;

exports.singleton = singleton;
exports.repeat = repeat;
exports.range = range;
exports.cons = cons;
exports.map = map;
exports.mapi = mapi;
exports.foldl = foldl;
exports.foldr = foldr;
exports.filter = filter;
exports.filterMap = filterMap;
exports.length = length;
exports.reverse = reverse;
exports.has = has;
exports.all = all;
exports.any = any;
exports.max = max;
exports.min = min;
exports.sum = sum;
exports.product = product;
exports.append = append;
exports.concat = concat;
exports.concatMap = concatMap;
exports.intersperse = intersperse;
exports.map2 = map2;
exports.map3 = map3;
exports.map4 = map4;
exports.map5 = map5;
exports.sort = sort;
exports.sortBy = sortBy;
exports.sortWith = sortWith;
exports.isEmpty = isEmpty;
exports.head = head;
exports.tail = tail;
exports.take = take;
exports.drop = drop;
exports.partition = partition;
exports.unzip = unzip;
exports.$plus$plus = $plus$plus;
/* No side effect */
