// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var sqrt = /* () */0;

var logBase = /* () */0;

var e = /* () */0;

var pi = /* () */0;

var cos = /* () */0;

var sin = /* () */0;

var tan = /* () */0;

var acos = /* () */0;

var asin = /* () */0;

var atan = /* () */0;

var atan2 = /* () */0;

exports.sqrt = sqrt;
exports.logBase = logBase;
exports.e = e;
exports.pi = pi;
exports.cos = cos;
exports.sin = sin;
exports.tan = tan;
exports.acos = acos;
exports.asin = asin;
exports.atan = atan;
exports.atan2 = atan2;
/* No side effect */
