// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var pair = /* () */0;

var first = /* () */0;

var second = /* () */0;

var mapFirst = /* () */0;

var mapSecond = /* () */0;

var mapBoth = /* () */0;

exports.pair = pair;
exports.first = first;
exports.second = second;
exports.mapFirst = mapFirst;
exports.mapSecond = mapSecond;
exports.mapBoth = mapBoth;
/* No side effect */
