// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function fromInt(prim) {
  return String(prim);
}

var isEmpty = /* () */0;

var length = /* () */0;

var reverse = /* () */0;

var repeat = /* () */0;

var replace = /* () */0;

var append = /* () */0;

var concat = /* () */0;

var split = /* () */0;

var join = /* () */0;

var words = /* () */0;

var lines = /* () */0;

var slice = /* () */0;

var left = /* () */0;

var right = /* () */0;

var dropLeft = /* () */0;

var dropRight = /* () */0;

var contains = /* () */0;

var startsWith = /* () */0;

var endsWith = /* () */0;

var indexes = /* () */0;

var indices = /* () */0;

var toInt = /* () */0;

var toFloat = /* () */0;

var fromFloat = /* () */0;

var fromChar = /* () */0;

var cons = /* () */0;

var uncons = /* () */0;

var toList = /* () */0;

var fromList = /* () */0;

var toUpper = /* () */0;

var toLower = /* () */0;

var pad = /* () */0;

var padLeft = /* () */0;

var padRight = /* () */0;

var trim = /* () */0;

var trimLeft = /* () */0;

var trimRight = /* () */0;

var map = /* () */0;

var filter = /* () */0;

var reduce = /* () */0;

var reduceRight = /* () */0;

var any = /* () */0;

var all = /* () */0;

exports.isEmpty = isEmpty;
exports.length = length;
exports.reverse = reverse;
exports.repeat = repeat;
exports.replace = replace;
exports.append = append;
exports.concat = concat;
exports.split = split;
exports.join = join;
exports.words = words;
exports.lines = lines;
exports.slice = slice;
exports.left = left;
exports.right = right;
exports.dropLeft = dropLeft;
exports.dropRight = dropRight;
exports.contains = contains;
exports.startsWith = startsWith;
exports.endsWith = endsWith;
exports.indexes = indexes;
exports.indices = indices;
exports.toInt = toInt;
exports.fromInt = fromInt;
exports.toFloat = toFloat;
exports.fromFloat = fromFloat;
exports.fromChar = fromChar;
exports.cons = cons;
exports.uncons = uncons;
exports.toList = toList;
exports.fromList = fromList;
exports.toUpper = toUpper;
exports.toLower = toLower;
exports.pad = pad;
exports.padLeft = padLeft;
exports.padRight = padRight;
exports.trim = trim;
exports.trimLeft = trimLeft;
exports.trimRight = trimRight;
exports.map = map;
exports.filter = filter;
exports.reduce = reduce;
exports.reduceRight = reduceRight;
exports.any = any;
exports.all = all;
/* No side effect */
