// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Core__Pervasives = require("./Core__Pervasives.bs.js");

var Bool = 0;

var Fn = 0;

var Int = 0;

var List = 0;

var $$Math = 0;

var $$Option = 0;

var Result = 0;

var $$String = 0;

var Tuple = 0;

var $great$great = Core__Pervasives.$great$great;

var $less$less = Core__Pervasives.$less$less;

var $pipe$great = Core__Pervasives.$pipe$great;

var $less$pipe = Core__Pervasives.$less$pipe;

var $plus$plus = Core__Pervasives.$plus$plus;

exports.Bool = Bool;
exports.Fn = Fn;
exports.Int = Int;
exports.List = List;
exports.$$Math = $$Math;
exports.$$Option = $$Option;
exports.Result = Result;
exports.$$String = $$String;
exports.Tuple = Tuple;
exports.$great$great = $great$great;
exports.$less$less = $less$less;
exports.$pipe$great = $pipe$great;
exports.$less$pipe = $less$pipe;
exports.$plus$plus = $plus$plus;
/* No side effect */
