// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("../../src/Realm.bs.js");
var Core__List = require("../../src/core/Core__List.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Realm__Core = require("../../src/core/Realm__Core.bs.js");
var Core__Option = require("../../src/core/Core__Option.bs.js");
var Core__String = require("../../src/core/Core__String.bs.js");

function create(description, id) {
  return /* record */[
          /* description */description,
          /* completed */false,
          /* editing */false,
          /* id */id
        ];
}

var Entry = /* module */[/* create */create];

var emptyModel = /* record */[
  /* entries : [] */0,
  /* field */"",
  /* uid */0,
  /* visibility */"All"
];

var LocalStorage = /* module */[];

var Json = /* module */[];

function init(param) {
  return Realm__Core.$pipe$great(Realm__Core.$pipe$great(Caml_option.nullable_to_opt(localStorage.getItem("realm-todo-save")), (function (param) {
                    return Core__Option.andThen((function (prim) {
                                  return Caml_option.nullable_to_opt(JSON.parse(prim));
                                }), param);
                  })), (function (param) {
                return Core__Option.withDefault(emptyModel, param);
              }));
}

var partial_arg = Realm.Effect[/* map */5];

function persist(param) {
  return partial_arg((function (model) {
                return model;
              }), (function (param, model) {
                Realm__Core.$pipe$great(Caml_option.nullable_to_opt(JSON.stringify(model)), (function (param) {
                        return Core__Option.map((function (param) {
                                      localStorage.setItem("realm-todo-save", param);
                                      return /* () */0;
                                    }), param);
                      }));
                return model;
              }), param);
}

var add = Realm.Effect[/* update */2]((function (model) {
        return /* record */[
                /* entries */model[/* field */1] === "" ? model[/* entries */0] : Pervasives.$at(model[/* entries */0], /* :: */[
                        create(model[/* field */1], model[/* uid */2]),
                        /* [] */0
                      ]),
                /* field */"",
                /* uid */model[/* uid */2] + 1 | 0,
                /* visibility */model[/* visibility */3]
              ];
      }));

function updateField(str) {
  return Realm.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */model[/* entries */0],
                        /* field */str,
                        /* uid */model[/* uid */2],
                        /* visibility */model[/* visibility */3]
                      ];
              }));
}

function editingEntry(id, isEditing) {
  var updateEntry = function (t) {
    if (t[/* id */3] === id) {
      return /* record */[
              /* description */t[/* description */0],
              /* completed */t[/* completed */1],
              /* editing */isEditing,
              /* id */t[/* id */3]
            ];
    } else {
      return t;
    }
  };
  return Realm.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.map(updateEntry, model[/* entries */0]),
                        /* field */model[/* field */1],
                        /* uid */model[/* uid */2],
                        /* visibility */model[/* visibility */3]
                      ];
              }));
}

function updateEntry(id, task) {
  var updateEntry$1 = function (t) {
    if (t[/* id */3] === id) {
      return /* record */[
              /* description */task,
              /* completed */t[/* completed */1],
              /* editing */t[/* editing */2],
              /* id */t[/* id */3]
            ];
    } else {
      return t;
    }
  };
  return Realm.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.map(updateEntry$1, model[/* entries */0]),
                        /* field */model[/* field */1],
                        /* uid */model[/* uid */2],
                        /* visibility */model[/* visibility */3]
                      ];
              }));
}

function $$delete(id) {
  return Realm.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.filter((function (t) {
                                  return t[/* id */3] !== id;
                                }))(model[/* entries */0]),
                        /* field */model[/* field */1],
                        /* uid */model[/* uid */2],
                        /* visibility */model[/* visibility */3]
                      ];
              }));
}

var deleteComplete = Realm.Effect[/* update */2]((function (model) {
        return /* record */[
                /* entries */Core__List.filter((function (t) {
                          return !t[/* completed */1];
                        }))(model[/* entries */0]),
                /* field */model[/* field */1],
                /* uid */model[/* uid */2],
                /* visibility */model[/* visibility */3]
              ];
      }));

function check(id, isCompleted) {
  var updateEntry = function (t) {
    if (t[/* id */3] === id) {
      return /* record */[
              /* description */t[/* description */0],
              /* completed */isCompleted,
              /* editing */t[/* editing */2],
              /* id */t[/* id */3]
            ];
    } else {
      return t;
    }
  };
  return Realm.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.map(updateEntry, model[/* entries */0]),
                        /* field */model[/* field */1],
                        /* uid */model[/* uid */2],
                        /* visibility */model[/* visibility */3]
                      ];
              }));
}

function checkAll(isCompleted) {
  var updateEntry = function (t) {
    return /* record */[
            /* description */t[/* description */0],
            /* completed */isCompleted,
            /* editing */t[/* editing */2],
            /* id */t[/* id */3]
          ];
  };
  return Realm.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */Core__List.map(updateEntry, model[/* entries */0]),
                        /* field */model[/* field */1],
                        /* uid */model[/* uid */2],
                        /* visibility */model[/* visibility */3]
                      ];
              }));
}

function changeVisibility(visibility) {
  return Realm.Effect[/* update */2]((function (model) {
                return /* record */[
                        /* entries */model[/* entries */0],
                        /* field */model[/* field */1],
                        /* uid */model[/* uid */2],
                        /* visibility */visibility
                      ];
              }));
}

var update = persist;

var Html = Realm.MakeHtml(/* module */[]);

function onEnter(action) {
  return Realm__Core.$less$pipe(Html[/* Attr */0][/* onKeyDown */9], (function (keyCode) {
                if (keyCode === 13) {
                  return action;
                } else {
                  return Realm.Effect[/* none */0];
                }
              }));
}

function viewInput(task) {
  var func = Html[/* input */17];
  var arg = /* :: */[
    Curry._1(Html[/* Attr */0][/* autofocus */1], true),
    /* :: */[
      Curry._1(Html[/* Attr */0][/* name */3], "newTodo"),
      /* :: */[
        Curry._1(Html[/* Attr */0][/* onInput */8], updateField),
        /* :: */[
          onEnter(add),
          /* [] */0
        ]
      ]
    ]
  ];
  var arg$1 = /* `Text */[
    936573133,
    task
  ];
  var arg$2 = function (param) {
    return Curry._5(func, "What needs to be done?", param, "new-todo", arg, arg$1);
  };
  return Curry._4(Html[/* header */7], undefined, "header", undefined, /* :: */[
              Curry._4(Html[/* h1 */8], undefined, undefined, undefined, /* :: */[
                    Curry._1(Html[/* text */3], "todos"),
                    /* [] */0
                  ]),
              /* :: */[
                (function (eta) {
                    return Curry._1(arg$2(undefined), eta);
                  }),
                /* [] */0
              ]
            ]);
}

function viewEntry(todo) {
  var func = Html[/* input */17];
  var arg = /* :: */[
    Curry._1(Html[/* Attr */0][/* onClick */4], check(todo[/* id */3], !todo[/* completed */1])),
    /* [] */0
  ];
  var arg_001 = todo[/* completed */1];
  var arg$1 = /* `Checkbox */[
    111644259,
    arg_001
  ];
  var arg$2 = function (param, param$1) {
    return Curry._5(func, param, param$1, "toggle", arg, arg$1);
  };
  var func$1 = Html[/* input */17];
  var arg$3 = "todo-" + String(todo[/* id */3]);
  var partial_arg = todo[/* id */3];
  var arg$4 = /* :: */[
    Curry._1(Html[/* Attr */0][/* onInput */8], (function (param) {
            return updateEntry(partial_arg, param);
          })),
    /* :: */[
      Curry._1(Html[/* Attr */0][/* onBlur */7], editingEntry(todo[/* id */3], false)),
      /* :: */[
        onEnter(editingEntry(todo[/* id */3], false)),
        /* [] */0
      ]
    ]
  ];
  var arg_001$1 = todo[/* description */0];
  var arg$5 = /* `Text */[
    936573133,
    arg_001$1
  ];
  var arg$6 = function (param) {
    return Curry._5(func$1, param, arg$3, "edit", arg$4, arg$5);
  };
  return Curry._4(Html[/* li */12], undefined, todo[/* editing */2] ? "editing" : "", undefined, /* :: */[
              Curry._4(Html[/* div */6], undefined, "view", undefined, /* :: */[
                    (function (eta) {
                        return Curry._1(arg$2(undefined, undefined), eta);
                      }),
                    /* :: */[
                      Curry._5(Html[/* label */16], undefined, /* :: */[
                            Curry._1(Html[/* Attr */0][/* onDoubleClick */5], editingEntry(todo[/* id */3], true)),
                            /* [] */0
                          ], undefined, undefined, /* :: */[
                            Curry._1(Html[/* text */3], todo[/* description */0]),
                            /* [] */0
                          ]),
                      /* :: */[
                        Curry._4(Html[/* button */4], undefined, "destroy", /* :: */[
                              Curry._1(Html[/* Attr */0][/* onClick */4], $$delete(todo[/* id */3])),
                              /* [] */0
                            ], /* [] */0),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* :: */[
                (function (eta) {
                    return Curry._1(arg$6(undefined), eta);
                  }),
                /* [] */0
              ]
            ]);
}

function viewEntries(visibility, entries) {
  var isVisible = function (todo) {
    switch (visibility) {
      case "Active" : 
          return !todo[/* completed */1];
      case "Completed" : 
          return todo[/* completed */1];
      default:
        return true;
    }
  };
  var allCompleted = Core__List.all((function (t) {
          return t[/* completed */1];
        }), entries);
  var func = Html[/* input */17];
  var arg = /* :: */[
    Curry._1(Html[/* Attr */0][/* name */3], "toggle-all"),
    /* :: */[
      Curry._1(Html[/* Attr */0][/* onClick */4], checkAll(!allCompleted)),
      /* [] */0
    ]
  ];
  var arg$1 = /* `Checkbox */[
    111644259,
    allCompleted
  ];
  var arg$2 = function (param, param$1) {
    return Curry._5(func, param, param$1, "toggle-all", arg, arg$1);
  };
  return Curry._4(Html[/* section */9], undefined, "main", undefined, /* :: */[
              (function (eta) {
                  return Curry._1(arg$2(undefined, undefined), eta);
                }),
              /* :: */[
                Curry._5(Html[/* label */16], "toggle-all", undefined, undefined, undefined, /* :: */[
                      Curry._1(Html[/* text */3], "Mark all as complete"),
                      /* [] */0
                    ]),
                /* :: */[
                  Realm__Core.$less$pipe((function (eta) {
                          var func = Html[/* ul */11];
                          return Curry._2((function (param) {
                                          return Curry._2(func, param, "todo-list");
                                        })(undefined), undefined, eta);
                        }), Realm__Core.$pipe$great(Realm__Core.$pipe$great(entries, Core__List.filter(isVisible)), (function (param) {
                              return Core__List.map(viewEntry, param);
                            }))),
                  /* [] */0
                ]
              ]
            ]);
}

function viewControlsCount(entriesLeft) {
  var item = entriesLeft === 1 ? " item" : " items";
  return Curry._4(Html[/* span */10], undefined, "todo-count", undefined, /* :: */[
              Curry._4(Html[/* strong */13], undefined, undefined, undefined, /* :: */[
                    Curry._1(Html[/* text */3], Core__String.fromInt(entriesLeft)),
                    /* [] */0
                  ]),
              /* :: */[
                Curry._1(Html[/* text */3], item + " left"),
                /* [] */0
              ]
            ]);
}

function visibilitySwap(uri, visibility, actualVisibility) {
  return Curry._4(Html[/* li */12], undefined, undefined, /* :: */[
              Curry._1(Html[/* Attr */0][/* onClick */4], changeVisibility(visibility)),
              /* [] */0
            ], /* :: */[
              Curry._5(Html[/* a */15], uri, undefined, undefined, visibility === actualVisibility ? "selected" : "", /* :: */[
                    Curry._1(Html[/* text */3], visibility),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function viewControlsFilters(visibility) {
  return Curry._4(Html[/* ul */11], undefined, "filters", undefined, /* :: */[
              visibilitySwap("#/", "All", visibility),
              /* :: */[
                Curry._1(Html[/* text */3], " "),
                /* :: */[
                  visibilitySwap("#/active", "Active", visibility),
                  /* :: */[
                    Curry._1(Html[/* text */3], " "),
                    /* :: */[
                      visibilitySwap("#/completed", "Completed", visibility),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

function viewControlsClear(entriesCompleted) {
  return Curry._4(Html[/* button */4], undefined, "clear-completed", /* :: */[
              Curry._1(Html[/* Attr */0][/* hidden */2], entriesCompleted === 0),
              /* :: */[
                Curry._1(Html[/* Attr */0][/* onClick */4], deleteComplete),
                /* [] */0
              ]
            ], /* :: */[
              Curry._1(Html[/* text */3], "Clear completed (" + (Core__String.fromInt(entriesCompleted) + ")")),
              /* [] */0
            ]);
}

function viewControls(visibility, entries) {
  var entriesCompleted = Realm__Core.$pipe$great(Realm__Core.$pipe$great(entries, Core__List.filter((function (t) {
                  return t[/* completed */1];
                }))), Core__List.length);
  var entriesLeft = Core__List.length(entries) - entriesCompleted | 0;
  return Curry._4(Html[/* footer */5], undefined, "footer", /* :: */[
              Curry._1(Html[/* Attr */0][/* hidden */2], entries === /* [] */0),
              /* [] */0
            ], /* :: */[
              viewControlsCount(entriesLeft),
              /* :: */[
                viewControlsFilters(visibility),
                /* :: */[
                  viewControlsClear(entriesCompleted),
                  /* [] */0
                ]
              ]
            ]);
}

var infoFooter = Curry._4(Html[/* footer */5], undefined, "info", undefined, /* :: */[
      Curry._4(Html[/* p */14], undefined, undefined, undefined, /* :: */[
            Curry._1(Html[/* text */3], "Double-click to edit a todo"),
            /* [] */0
          ]),
      /* :: */[
        Curry._4(Html[/* p */14], undefined, undefined, undefined, /* :: */[
              Curry._1(Html[/* text */3], "Written by "),
              /* :: */[
                Curry._5(Html[/* a */15], "https://github.com/glennsl", undefined, undefined, undefined, /* :: */[
                      Curry._1(Html[/* text */3], "Glenn Slotte"),
                      /* [] */0
                    ]),
                /* [] */0
              ]
            ]),
        /* :: */[
          Curry._4(Html[/* p */14], undefined, undefined, undefined, /* :: */[
                Curry._1(Html[/* text */3], "Based on "),
                /* :: */[
                  Curry._5(Html[/* a */15], "https://github.com/evancz/elm-todomvc", undefined, undefined, undefined, /* :: */[
                        Curry._1(Html[/* text */3], "evancz/elm-todomvc"),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]),
          /* :: */[
            Curry._4(Html[/* p */14], undefined, undefined, undefined, /* :: */[
                  Curry._1(Html[/* text */3], "Part of "),
                  /* :: */[
                    Curry._5(Html[/* a */15], "http://todomvc.com", undefined, undefined, undefined, /* :: */[
                          Curry._1(Html[/* text */3], "TodoMVC"),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

function view(model) {
  return Curry._4(Html[/* div */6], undefined, "todomvc-wrapper", undefined, /* :: */[
              Curry._4(Html[/* section */9], undefined, "todoapp", undefined, /* :: */[
                    viewInput(model[/* field */1]),
                    /* :: */[
                      viewEntries(model[/* visibility */3], model[/* entries */0]),
                      /* :: */[
                        viewControls(model[/* visibility */3], model[/* entries */0]),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* :: */[
                infoFooter,
                /* [] */0
              ]
            ]);
}

Realm.mountHtml("todoapp")(init, update, undefined, view, /* () */0);

exports.Entry = Entry;
exports.emptyModel = emptyModel;
exports.LocalStorage = LocalStorage;
exports.Json = Json;
exports.init = init;
exports.persist = persist;
exports.add = add;
exports.updateField = updateField;
exports.editingEntry = editingEntry;
exports.updateEntry = updateEntry;
exports.$$delete = $$delete;
exports.deleteComplete = deleteComplete;
exports.check = check;
exports.checkAll = checkAll;
exports.changeVisibility = changeVisibility;
exports.update = update;
exports.Html = Html;
exports.onEnter = onEnter;
exports.viewInput = viewInput;
exports.viewEntry = viewEntry;
exports.viewEntries = viewEntries;
exports.viewControlsCount = viewControlsCount;
exports.visibilitySwap = visibilitySwap;
exports.viewControlsFilters = viewControlsFilters;
exports.viewControlsClear = viewControlsClear;
exports.viewControls = viewControls;
exports.infoFooter = infoFooter;
exports.view = view;
/* add Not a pure module */
