// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Realm = require("./Realm.bs.js");
var Thing1 = require("./Thing1.bs.js");
var Thing2 = require("./Thing2.bs.js");
var Component1 = require("./Component1.bs.js");
var Component2 = require("./Component2.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component1.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component2.make("Hello!", /* array */[])), "index2");

Realm.App[/* mount */1]("thing1", (function () {
        return /* () */0;
      }), (function (_, _$1) {
        return /* () */0;
      }), (function (param) {
        return Thing1.view("hello", param);
      }));

Realm.App[/* mount */1]("thing2", Thing2.init, Thing2.update, (function (param) {
        return Thing2.view("hello", param);
      }));

/*  Not a pure module */
