// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Realm = require("./Realm.bs.js");

function view(message, _, _$1) {
  return Realm.Html[/* div */2](/* Some */[(function () {
                  console.log("clicky!");
                  return /* () */0;
                })], /* :: */[
              Realm.Html[/* text */1](message),
              /* [] */0
            ]);
}

exports.view = view;
/* Realm Not a pure module */
