// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Realm = require("./Realm.bs.js");

var Html = Curry._1(Realm.App[/* Html */0], /* module */[]);

function init() {
  return /* record */[
          /* count */0,
          /* show */true
        ];
}

function update(msg, model) {
  if (msg) {
    return /* record */[
            /* count */model[/* count */0],
            /* show */!model[/* show */1]
          ];
  } else {
    return /* record */[
            /* count */model[/* count */0] + 1 | 0,
            /* show */model[/* show */1]
          ];
  }
}

function view(greeting, model) {
  var message = "You've clicked this " + (String(model[/* count */0]) + " times(s)");
  var match = model[/* show */1];
  return Curry._2(Html[/* div */3], /* [] */0, /* :: */[
              Curry._2(Html[/* button */4], /* :: */[
                    Curry._1(Html[/* onClick */0], /* Click */0),
                    /* [] */0
                  ], /* :: */[
                    Curry._1(Html[/* text */2], message),
                    /* [] */0
                  ]),
              /* :: */[
                Curry._2(Html[/* button */4], /* :: */[
                      Curry._1(Html[/* onClick */0], /* Toggle */1),
                      /* [] */0
                    ], /* :: */[
                      Curry._1(Html[/* text */2], "Toggle greeting"),
                      /* [] */0
                    ]),
                /* :: */[
                  match ? Curry._1(Html[/* text */2], greeting) : Html[/* null */1],
                  /* [] */0
                ]
              ]
            ]);
}

exports.Html = Html;
exports.init = init;
exports.update = update;
exports.view = view;
/* Html Not a pure module */
